### ISSUE TITLE
Unpublished previews not running/returning page template queries

### ISSUE THREAD

**Issue by mrseanbaines** [prismicio/gatsby#423] opened 2021-08-09 12:32 UTC
I'm facing an issue where, when previewing an unpublished document, data passed to the `data` prop in my page template component is returning something other than what I queried for.

I am querying some data in a blog post template and trying to preview an unpublished document via Prismic. The preview works fine for published documents, but for unpublished posts it returns the 404 page query result, and also `prismicBlogPost` (but not `prismicBlogSignupBanner` or `allPrismicBlogPost`). What's even more weird is that even if I remove `prismicBlogPost` from the query, it still shows up in the response. I'm not sure if even that field is respecting what I am querying in `prismicBlogPost` since the result seems to return everything on the blog post whether I've queried it or not.

I'm using the `_previewable` field on all documents. I'm also querying for `id` everywhere possible as I think I read somewhere that this is necessary(?). I'm also using the `withPrismicPreview` HOC in my blog post template and the `withPrismicUnpublishedPreview` HOC in my 404 page template.

This is the query exactly as I am doing it in the code:
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/24367010/128704450-3447e305-9e30-4684-8e04-342084d007da.png">

This is the response when previewing a **published** document (same as in GraphiQL editor):
<img width="776" alt="image" src="https://user-images.githubusercontent.com/24367010/128704636-f8cfff5e-96ee-42f7-84fa-3724f3c7fd5d.png">

This is the response when previewing an **unpublished** document (this also seems to return everything from the document, rather than just what I queried for):
<img width="731" alt="image" src="https://user-images.githubusercontent.com/24367010/128704797-a20cf15f-e332-4a21-ad2f-6def663e9aaa.png">

### Versions

- gatsby-source-prismic: v4.0.1
- gatsby-plugin-prismic-previews: v4.0.1
- node: v14.17.1

### Steps to reproduce
Set up Prismic previews, add a query to a template, start a preview session, try to access the data queried in the template.

### What is expected?
The `data` prop in my page template component should receive everything queried in the graphql query

### What is actually happening?
Content from the query in the 404 page is returned, along with some general data for the document type I am trying to preview (but not the data I actually queried)

**Comment by angeloashmore** [comment] 2021-08-09 18:46
Hey @mrseanbaines, thank you for the detailed report!

This behavior is how the plugin is designed and I understand that this may not be expected.

You are correct in saying your page query will be ignored for _unpublished_ previews. Unpublished previews technically do not exist in your site so Gatsby has no query or content to associate with it. Published previews have access to your page's query, so the preview plugin can be smart about how it provides updated content.

When running unpublished previews in the browser, we no longer have access to Gatsby's GraphQL server. As such, you are not able to make arbitrary queries. Instead, the best we can do is provide you with the Prismic document(s) that matches the URL.

In your case, this is a `prismicBlogPost` since the URL to the page resolves to that document (it is resolved using your Link Resolver).

If your page needs static data, like your `prismicBlogSignupBanner` and `allPrismicBlogPost`, you can include those in your page template using Gatsby's `useStaticQuery`. This will move the query data into the component itself, which will be available during a Prismic preview.

See: https://github.com/prismicio/gatsby/blob/main/packages/gatsby-plugin-prismic-previews/docs/limitations.md

**Comment by angeloashmore** [comment] 2021-08-09 18:55
I'm going to close this issue as this is expected behavior, but we can continue the conversation if you have suggestions on how this could be handled differently. We can always re-open the issue if necessary. :)

**Closed by angeloashmore** 2021-08-09 18:55 UTC
Labels: bug, V4

**Comment by mrseanbaines** [comment] 2021-08-09 19:09
Hey @angeloashmore. Thanks for the quick response.

I have tried to avoid static queries as much as possible as I am working with a multi-locale site, so since you can't provide variables such as locales to the static queries, I end up having to query _all_ documents in all locales and then filter only the locale I care about for a given page 😕. It sounds like this might be the only option though so thanks for the suggestion.

I don't really have any ideas/suggestions on how this could be handled differently, although I work on another site that uses the `gatsby-source-prismic-graphql` plugin and that somehow manages to get unpublished previews working (also GQL field aliasing), so maybe there are some ideas in that plugin's source. That plugin is super buggy though so I definitely wouldn't be looking to switch over for this project.

**Comment by angeloashmore** [comment] 2021-08-09 19:22
I see, that makes sense. If you need to support unpublished previews, then yes, `useStaticQuery` with client-side filtering seems to be the only option.

As an alternative preview setup, you could use Gatsby Cloud Previews. This effectively runs your Gatsby development server in the cloud which supports unpublished previews with page-level queries like you posted. It requires a specific workflow (publishing your documents to a Release to preview) so it depends on what makes sense for you and your team.

You can learn more about it here: https://prismic.io/docs/technologies/prismic-gatsby-cloud

The `-graphql` plugin does a lot of magic by changing the internal Babel plugins that Gatsby uses. It then runs your GraphQL query in the client directly to Prismic's GraphQL API. It's very clever, but as you said, can be fairly buggy and difficult to maintain.
